# Generated by Django 5.1.15 on 2026-09-18 23:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Token UUIDv4 impreso en credencial')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo y vigente'), ('REVOKED', 'Revocado (extravío o reemisión)'), ('EXPIRED', 'Expirado (fin de ciclo)')], db_index=True, default='ACTIVE', max_length=15, verbose_name='Estado del token')),
                ('hmac_signature', models.CharField(blank=True, editable=False, max_length=64, verbose_name='Firma criptográfica HMAC-SHA256')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de emisión')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de revocación')),
                ('revocation_reason', models.CharField(blank=True, default='', max_length=150, verbose_name='Motivo de revocación (ej: extravío, daño, reposición)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_tokens', to='students.student', verbose_name='Estudiante titular')),
            ],
            options={
                'verbose_name': 'Token de Credencial QR',
                'verbose_name_plural': 'Tokens de Credenciales QR',
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student',), name='unique_active_qr_token_per_student')],
            },
        ),
    ]
