# Generated by Django 5.1.15 on 2026-09-18 23:57

import apps.students.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo del tutor')),
                ('phone_number', models.CharField(max_length=10, validators=[apps.students.validators.validate_phone_number], verbose_name='Teléfono celular (10 dígitos)')),
                ('relationship', models.CharField(choices=[('MADRE', 'Madre'), ('PADRE', 'Padre'), ('TUTOR_LEGAL', 'Tutor Legal'), ('ABUELO_A', 'Abuelo / Abuela'), ('OTRO', 'Otro Familiar / Tutor Autorizado')], default='TUTOR_LEGAL', max_length=25, verbose_name='Parentesco o vínculo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico (opcional)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observaciones o indicaciones especiales')),
            ],
            options={
                'verbose_name': 'Tutor Legal',
                'verbose_name_plural': 'Tutores Legales',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('enrollment_id', models.CharField(db_index=True, max_length=20, unique=True, validators=[apps.students.validators.validate_enrollment_id], verbose_name='Matrícula / Código escolar')),
                ('curp', models.CharField(db_index=True, max_length=18, unique=True, validators=[apps.students.validators.validate_curp], verbose_name='CURP Oficial (RENAPO)')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('last_name_father', models.CharField(max_length=100, verbose_name='Primer apellido (Paterno)')),
                ('last_name_mother', models.CharField(blank=True, default='', max_length=100, verbose_name='Segundo apellido (Materno)')),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, '1°'), (2, '2°'), (3, '3°')], verbose_name='Grado escolar')),
                ('group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1, verbose_name='Grupo')),
                ('shift', models.CharField(choices=[('MATUTINO', 'Turno Matutino'), ('VESPERTINO', 'Turno Vespertino')], default='MATUTINO', max_length=15, verbose_name='Turno')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo / Suspensión temporal'), ('GRADUATED', 'Egresado'), ('EXPELLED', 'Baja definitiva')], db_index=True, default='ACTIVE', max_length=15, verbose_name='Estado escolar')),
                ('medical_notes', models.TextField(blank=True, default='', verbose_name='Alergias o consideraciones médicas relevantes')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.guardian', verbose_name='Tutor legal registrado')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['grade', 'group', 'last_name_father', 'last_name_mother', 'first_name'],
                'indexes': [models.Index(fields=['grade', 'group', 'shift'], name='students_st_grade_67933d_idx'), models.Index(fields=['status'], name='students_st_status_5e2210_idx')],
            },
        ),
    ]
